apiVersion: v1
kind: Pod
metadata:
  name: nginx

spec:
  containers:
 # docker run -d --name nginx nginx
  - name: nginx
    image: nginx
    # ports:
    # - containerPort: 80 
    #this port we can or we can't give also work in public  beacuse 80 is public
